# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('universidad', models.CharField(max_length=100)),
                ('registro_profesional', models.CharField(max_length=100)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoRemitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AddField(
            model_name='medicoremitente',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.Especialidad', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicos.Especialidad', verbose_name='Especialidad'),
        ),
    ]
