# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_auto_20171007_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='universidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
