# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_auto_20171014_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.Especialidad', verbose_name='Especialidad'),
        ),
    ]
