# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_auto_20171014_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoremitente',
            name='especialidad_temporal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
