# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_auto_20171014_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='identificacion',
        ),
        migrations.AddField(
            model_name='especialista',
            name='apellido_segundo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialista',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20),
        ),
        migrations.AddField(
            model_name='especialista',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='nombre_segundo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='nro_identificacion',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialista',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=2),
        ),
    ]
