# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_auto_20171204_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo_especialistas',
            field=models.BooleanField(default=False),
        ),
    ]
