# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0010_especialidad_activo_especialistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='registro_profesional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
