# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0012_especialista_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='activo',
        ),
    ]
