# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0033_auto_20180112_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biopsia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion_macroscopica', models.TextField()),
                ('descripcion_microscopica', models.TextField()),
                ('diagnostico', models.TextField()),
                ('orden_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_biopsias', to='ordenes.OrdenExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
