# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0004_auto_20180113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsia',
            name='descripcion_macroscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biopsia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biopsia',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
