# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0006_citologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='citologia',
            name='asc_h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citologia',
            name='asc_us',
            field=models.BooleanField(default=False),
        ),
    ]
