# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20171014_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nro_identificacion',
            field=models.CharField(default=1112460778, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=2),
        ),
    ]
