# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20171014_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=20),
        ),
    ]
