# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20171118_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
