# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entidad', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(max_length=100, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_2', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_3', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_3', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
                'verbose_name': 'Entidad',
            },
        ),
    ]
