# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
