# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_auto_20171014_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoentidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
