# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_auto_20171014_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nit',
            field=models.CharField(max_length=100),
        ),
    ]
