# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_auto_20171025_1635'),
        ('entidades', '0006_auto_20171014_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_exame', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.Entidad')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.Examen')),
            ],
        ),
        migrations.AddField(
            model_name='entidad',
            name='examenes',
            field=models.ManyToManyField(through='entidades.EntidadExamen', to='examenes.Examen'),
        ),
    ]
