# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_auto_20171025_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadexamen',
            old_name='valor_exame',
            new_name='valor_examen',
        ),
    ]
