# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0008_auto_20171025_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadexamen',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_entidades', to='examenes.Examen'),
        ),
    ]
