# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_auto_20171025_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadexamen',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='entidades.Entidad'),
        ),
    ]
