# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0011_entidad_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoentidad',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='entidades.Entidad'),
        ),
    ]
