# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0012_auto_20171120_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadexamen',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
