# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codico_cups', models.PositiveIntegerField(help_text='Código de clasificación única en procedimientos en salud', unique=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del Examen')),
                ('nombre_corto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Examen (Corto)')),
                ('valor_referncia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valor de Referencia')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('tecnica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica')),
            ],
        ),
    ]
