# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='valor_referncia',
            new_name='valor_referencia',
        ),
    ]
