# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_auto_20171019_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='costo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor del Examen'),
        ),
    ]
