# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_examen_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='costo',
            new_name='costo_referencia',
        ),
    ]
