# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_auto_20171025_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenentidad',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='examenentidad',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='entidades',
        ),
        migrations.DeleteModel(
            name='ExamenEntidad',
        ),
    ]
