# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_auto_20171025_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='examen_grupo',
            field=models.ManyToManyField(related_name='_examen_examen_grupo_+', to='examenes.Examen'),
        ),
    ]
