# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0015_auto_20171125_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='categoria_cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='examenes.CupsCategoria'),
        ),
    ]
