# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0016_examen_categoria_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupscategoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupsgrupo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cupssubgrupo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
