# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0017_auto_20171125_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupscategoria',
            name='subgrupo',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='categoria_cups',
        ),
        migrations.AddField(
            model_name='examen',
            name='subgrupo_cups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='examenes.CupsSubGrupo'),
        ),
        migrations.DeleteModel(
            name='CupsCategoria',
        ),
    ]
