# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0014_auto_20180106_0743'),
        ('examenes', '0019_auto_20171209_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='especial',
            field=models.BooleanField(default=False, verbose_name='Plantilla Especial'),
        ),
        migrations.AddField(
            model_name='examen',
            name='especialista_firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_examenes_firmados_sencillos', to='medicos.Especialista'),
        ),
        migrations.AddField(
            model_name='examen',
            name='multifirma',
            field=models.BooleanField(default=False, verbose_name='Multiple Firma'),
        ),
        migrations.AddField(
            model_name='examen',
            name='nro_plantilla',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nro. Plantilla Especial'),
        ),
    ]
