# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0020_auto_20180106_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='especialista_firma',
        ),
    ]
