# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_paciente_genero'),
        ('entidades', '0006_auto_20171014_0953'),
        ('medicos', '0008_auto_20171014_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('relacion_cobro', 'Relación de Cobro'), ('cortesia', 'Cortesía')], default='efectivo', max_length=30)),
                ('nombre_contacto_alternativo', models.CharField(max_length=200, verbose_name='Nombre Contacto')),
                ('numero_contacto_alternativo', models.CharField(max_length=100, verbose_name='Número Contacto')),
                ('direccion_contacto_alternativo', models.CharField(max_length=200, verbose_name='Dirección Contacto')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_ordenes', to='entidades.Entidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_ordenes', to='pacientes.Paciente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_ordenes', to='medicos.MedicoRemitente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
