# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_auto_20171019_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='remitente',
        ),
    ]
