# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_auto_20171014_1046'),
        ('ordenes', '0003_remove_orden_remitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='medico_remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_ordenes', to='medicos.MedicoRemitente'),
        ),
    ]
