# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20171026_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Descuento'),
        ),
        migrations.AddField(
            model_name='orden',
            name='valor_final',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Final'),
        ),
        migrations.AddField(
            model_name='orden',
            name='valor_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
