# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0014_remove_examen_examenes'),
        ('ordenes', '0006_auto_20171104_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_resultado', models.CharField(max_length=300)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='examenes.Examen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ordenes.Orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='examenes',
            field=models.ManyToManyField(related_name='mis_examenes', through='ordenes.OrdenExamen', to='examenes.Examen'),
        ),
    ]
