# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_auto_20171104_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenexamen',
            old_name='valor_resultado',
            new_name='resultado',
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='examen_codigo_cups',
            field=models.PositiveIntegerField(default=0, help_text='Código de clasificación única en procedimientos en salud', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='examen_nombre',
            field=models.CharField(default='hola', max_length=300, verbose_name='Nombre del Examen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='examen_unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Descuento'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='valor_final',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Final'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='valor_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
