# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_auto_20171117_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_examenes', to='ordenes.Orden'),
        ),
    ]
