# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_auto_20171117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='examen_codigo_cups',
            field=models.PositiveIntegerField(help_text='Código de clasificación única en procedimientos en salud'),
        ),
    ]
