# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_auto_20171117_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='descuento',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
