# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_ordenexamen_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='descuento',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
