# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_auto_20171118_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='examen_estado',
            field=models.PositiveIntegerField(choices=[(0, 'Creado'), (1, 'En proceso'), (2, 'Terminado'), (3, 'Verificado'), (4, 'Impreso')], default=0),
        ),
    ]
