# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_ordenexamen_examen_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='examen_estado',
            field=models.PositiveIntegerField(choices=[(0, 'Creado'), (1, 'En proceso'), (2, 'Con Resultados'), (3, 'Verificado'), (4, 'Impreso')], default=0),
        ),
    ]
