# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_auto_20171118_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tipo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('RELACION DE COBRO', 'Relación de Cobro'), ('CORTESIA', 'Cortesía')], default='efectivo', max_length=30),
        ),
    ]
