# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_auto_20171204_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='tecnica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='valor_referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Valor de Referencia'),
        ),
    ]
