# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_auto_20171209_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenexamen',
            name='unidad_medida',
        ),
    ]
