# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0020_remove_ordenexamen_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='paciente_nombre',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
    ]
