# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_auto_20171209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='resultado',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
