# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0023_auto_20171209_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOrdenExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_bitacora', models.CharField(max_length=100)),
                ('examen_estado', models.PositiveIntegerField(default=0)),
                ('tecnica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica')),
                ('examen_valor_referencia', models.TextField(blank=True, null=True, verbose_name='Valor de Referencia')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('examen_nombre', models.CharField(max_length=300, verbose_name='Nombre del Examen')),
                ('examen_codigo_cups', models.PositiveIntegerField(help_text='Código de clasificación única en procedimientos en salud')),
                ('examen_unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('resultado', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('descuento', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('valor_total', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Total')),
                ('valor_descuento', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Descuento')),
                ('valor_final', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Final')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_bitacoras_orden_examen', to=settings.AUTH_USER_MODEL)),
                ('orden_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_bitacoras', to='ordenes.OrdenExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
