# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0024_historialordenexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='created_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='modificado_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
