# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_auto_20171209_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenexamen',
            old_name='created_por',
            new_name='creado_por',
        ),
    ]
