# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0013_remove_especialista_activo'),
        ('ordenes', '0028_auto_20171210_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamenFirmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_examenes_firmados', to='medicos.Especialista')),
                ('orden_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_firmas', to='ordenes.OrdenExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
