# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_ordenexamen_especialista_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenexamen',
            name='especialista_firma',
        ),
    ]
