# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0032_remove_ordenexamen_especialista_firma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenexamen',
            options={'permissions': [('orden_examen_firmar_como', 'Puede Firmar Examen como Otros'), ('orden_examen_verificar', 'Puede Verificar Examen'), ('orden_examen_cambiar_estado', 'Puede Cambiar Estado Examen')]},
        ),
    ]
