# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0034_auto_20180113_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
